version: 0.2
phases:
  install:
    runtime-versions:
      ####docker: 18

      ###https://github.com/aws/aws-codebuild-docker-images/issues/531

      docker: 20

  pre_build:
    commands:
      - echo "◆YI　Dockerイメージのビルド前ーーーーーーーーーーーーーー"   
      - echo 00000YITO Logging in to Amazon ECR...
      ##mod20221124
      ###- $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
      ###- $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      ###- aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin <Account ID>.dkr.ecr.ap-northeast-1.amazonaws.com

      ##01- aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      ##02- $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
      ####/codebuild/output/tmp/script.sh: 4: aws: not found

      ##03 https://ijianhuang.wordpress.com/2021/09/18/fixed-a-strange-error-script-sh-4-login-not-found-in-aws-codebuild/

      ##04 OKKK
      ###- aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 234944522256.dkr.ecr.ap-northeast-1.amazonaws.com
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo "◆YI　Dockerイメージのビルドーーーーーーーーーーーーーー" Building the Docker image...    
      - echo Build started on `date`
      - echo "◆" `head -1 ./docker-compose_aws.yml`
      ###- docker-compose -f ./docker-compose.yml build --no-cache webapp
      - docker-compose -f ./docker-compose_aws.yml build --no-cache webapp
      - docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}      
  post_build:
    commands:
      - echo "◆YI　Dockerイメージのビルド後ーーーーーーーーーーーーーー"   
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}
      


      
